name: Build Tweak
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-sdks: 'https://github.com/theos/sdks'

      - name: Build package
        run: |
          make package FINALPACKAGE=1 ARCHS="arm64e" TARGET="iphone:clang:16.5:15.0"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CallMeMaybe-deb
          path: packages/*.deb
